### ISSUE TITLE
:shield: Security vulnerabilities

### ISSUE THREAD

**Issue by hitisec** [jspark311/BuriedUnderTheNoiseFloor#3]
Hi,
Some potential security vulnerabilities has been identified in this repository.
Please Validate reports submitted on huntr and if are valid please mark them valid there.
The report links are the following:

https://huntr.dev/bounties/7461f0e7-b1d6-49f5-8e3d-0c2fc144ef16/
https://huntr.dev/bounties/44482baf-b885-4e29-a125-9ed0b2d39560/
https://huntr.dev/bounties/8ed7a501-3e32-4a38-8ba0-f09b45824bde/
https://huntr.dev/bounties/ba6de042-1235-42fe-8379-57b70d9c6c01/

**Comment by jspark311** [comment]
All of these vulnerabilities refer to the demonstration script, and NOT the library itself.
It is not intended that the end-user of this library use `form.php` for anything but as an example of how to use the library.

Nevertheless, I have made sure that PHP execution is disabled in the script's upload directory on the one webserver that has it deployed publicly.

To re-state: All of these vulnerabilities are fixed by ensuring the PHP execution policy is disabled for the upload directory on the webserver. Sophisticated users will re-write form.php into their own site views and infrastructure that (presumably) already has upload directories properly protected.
